typography_spectrum: 0.6210451161023229
color:
  saturation: 0.6985157229937613
  brandStrength: 0.2812983337789774
  rhythmicContrast: 0.2404817712958902
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  lightness: 0.9337090565823019
layout_spectrum: 0.5146185315679759
analytics:
  google: UA-79570743-1
author:
  name: Jarid Johnston
  email: jarid.johnston@gmail.com
  url: 'http://jaridpj.com'
name: Living My Best Year Ever
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Travel, Beaches, Fine Cigars, Fine Food, and Fine Women. #jaridpj #nomad'
