layout_spectrum: 1
name: Living My Best Year Ever
author:
  name: Jarid Johnston
  email: jarid.johnston@gmail.com
title: Less trying more Doing
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9043102734722197
color:
  brandStrength: 0.79198
  lightness: 0.787594
  saturation: 0.3602757
  rhythmicContrast: 0.147476
  brandColors:
    - '#4A2B0F'
    - '#754B1B'
    - '#966429'
    - '#BE8945'
    - '#F3C57C'
