layout_spectrum: 0.5845864
name: Living My Best Year Ever
author:
  name: Jarid Johnston
  email: jarid.johnston@gmail.com
title: Less trying more Doing
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9043102734722197
color:
  brandStrength: 0.6357445882167667
  lightness: 0.680434460984543
  saturation: 0.1460944965947419
  rhythmicContrast: 0.147476005833596
  brandColors:
    - '#4A2B0F'
    - '#754B1B'
    - '#966429'
    - '#BE8945'
    - '#F3C57C'
