typography_spectrum: 0.9981016113888472
color:
  saturation: 0.972986075328663
  brandStrength: 0.6113816993311048
  rhythmicContrast: 0.8648081817664206
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  lightness: 0.3460272401571274
layout_spectrum: 0.003208866575732827
analytics:
  google: UA-79570743-1
author:
  name: Jarid Johnston
  email: jarid.johnston@gmail.com
  url: 'http://jaridpj.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2aa9848-aaf0-4e40-b701-fcf39da688d1.jpg
name: Living My Best Year Ever
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/33a23b07-c534-4d61-95b6-14baa649e910.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Travel, Beaches, Fine Cigars, Fine Food, and Fine Women. #jaridpj #nomad'
