title: Living My Best Year Ever
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.972986075328663
  brandStrength: 0.6113816993311048
  lightness: 0.3460272401571274
  brandColors:
    - '#1C1C1C'
    - '#DA2D41'
    - '#497331'
    - '#7C0414'
    - '#BCC1AC'
  rhythmicContrast: 0.8648081817664206
analytics:
  google: UA-79570743-1
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/33a23b07-c534-4d61-95b6-14baa649e910.jpg
name: Living My Best Year Ever
author:
  name: Jarid Johnston
  email: jarid.johnston@gmail.com
  url: 'http://jaridpj.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2aa9848-aaf0-4e40-b701-fcf39da688d1.jpg
typography_spectrum: 0.6297872
layout_spectrum: 1
