layout_spectrum: 0.3214286
name: Living My Best Year Ever
author:
  name: Jarid Johnston
  email: jarid.johnston@gmail.com
title: Less trying more Doing
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9043102734722197
color:
  brandStrength: 0.6357445882167667
  saturation: 0.1460944965947419
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.680434460984543
  rhythmicContrast: 0.147476005833596
